# set according to http://www.eloratings.net/about

# to output all tournament types print the following line
#matches["tournament"].unique()

K = {
    "Friendly": 20,
    "British Championship": 30,
    "Copa Lipton": 30,
    "Copa Newton": 30,
    "Copa Premio Honor Argentino": 30,
    "Copa Premio Honor Uruguayo": 30,
    "Copa Roca": 30,
    "Copa América": 30,
    "Copa Chevallier Boutell": 30,
    "Nordic Championship": 30,
    "International Cup": 50,
    "Baltic Cup": 30,
    "Balkan Cup": 30,
    "FIFA World Cup": 60,
    "Copa Rio Branco": 30,
    "FIFA World Cup qualification": 40,
    "Bolivarian Games": 30,
    "CCCF Championship": 30,
    "NAFU Championship": 30,
    "Copa Oswaldo Cruz": 30,
    "Pan American Championship": 30,
    "Copa del Pacífico": 30,
    "Copa Bernardo O'Higgins": 30,
    "AFC Asian Cup qualification": 30,
    "Atlantic Cup": 30,
    "AFC Asian Cup": 30,
    "African Cup of Nations": 50,
    "Copa Paz del Chaco": 30,
    "Merdeka Tournament": 30,
    "UEFA Euro qualification": 40,
    "UEFA Euro": 50,
    "Windward Islands Tournament": 30,
    "African Cup of Nations qualification": 30,
    "Vietnam Independence Cup": 30,
    "Copa Carlos Dittborn": 30,
    "Phillip Seaga Cup": 30,
    "CONCACAF Championship": 30,
    "Copa Juan Pinto Durán": 30,
    "Arab Cup": 30,
    "South Pacific Games": 30,
    "CONCACAF Championship qualification": 30,
    "Copa Artigas": 30,
    "GaNEFo": 30,
    "King's Cup": 30,
    "Gulf Cup": 30,
    "Indonesia Tournament": 30,
    "Korea Cup": 30,
    "Palestine Cup": 30,
    "Brazil Independence Cup": 30,
    "Copa Ramón Castilla": 30,
    "Oceania Nations Cup": 30,
    "CECAFA Cup": 30,
    "Kuneitra Cup": 30,
    "Copa Félix Bogado": 30,
    "Real Madrid 75th Anniversary Cup": 30,
    "Beijing International Friendship Tournament": 30,
    "Kirin Cup": 30,
    "CFU Caribbean Cup qualification": 30,
    "CFU Caribbean Cup": 30,
    "Amílcar Cabral Cup": 30,
    "FIFA 75th Anniversary Cup": 30,
    "Guangzhou International Friendship Tournament": 30,
    "Mundialito": 30,
    "West African Cup": 30,
    "Nehru Cup": 30,
    "Merlion Cup": 30,
    "Great Wall Cup": 30,
    "UDEAC Cup": 30,
    "Rous Cup": 30,
    "CONMEBOL–UEFA Cup of Champions": 30,
    "Lunar New Year Cup": 30,
    "Arab Cup qualification": 30,
    "Tournoi de France": 30,
    "Malta International Tournament": 30,
    "Matthews Cup": 30,
    "Tournament Burkina Faso": 30,
    "Island Games": 30,
    "Dynasty Cup": 30,
    "Dakar Tournament": 30,
    "UNCAF Cup": 30,
    "Gold Cup": 30,
    "USA Cup": 30,
    "Jordan International Tournament": 30,
    "Confederations Cup": 40,
    "United Arab Emirates Friendship Tournament": 30,
    "Oceania Nations Cup qualification": 30,
    "Simba Tournament": 30,
    "SAFF Cup": 30,
    "AFF Championship": 30,
    "King Hassan II Tournament": 30,
    "Cyprus International Tournament": 30,
    "Dunhill Cup": 30,
    "COSAFA Cup qualification": 30,
    "COSAFA Cup": 30,
    "Gold Cup qualification": 30,
    "SKN Football Festival": 30,
    "UNIFFAC Cup": 30,
    "WAFF Championship": 30,
    "Millennium Cup": 30,
    "Cup of Ancient Civilizations": 30,
    "Prime Minister's Cup": 30,
    "EAFF Championship": 30,
    "TIFOCO Tournament": 30,
    "Afro-Asian Games": 30,
    "AFC Challenge Cup": 30,
    "FIFI Wild Cup": 30,
    "ELF Cup": 30,
    "Viva World Cup": 30,
    "AFC Challenge Cup qualification": 30,
    "African Nations Championship": 40,
    "VFF Cup": 30,
    "Dragon Cup": 30,
    "ABCS Tournament": 30,
    "Nile Basin Tournament": 30,
    "Nations Cup": 30,
    "Copa Confraternidad": 30,
    "Pacific Games": 30,
    "Superclásico de las Américas": 30,
    "Kirin Challenge Cup": 30,
    "OSN Cup": 30,
    "CONIFA World Football Cup": 30,
    "CONIFA European Football Cup": 30,
    "Copa América qualification": 30,
    "World Unity Cup": 30,
    "Pacific Mini Games": 30,
    "Intercontinental Cup": 40,
    "AFF Championship qualification": 30,
    "UEFA Nations League": 40,
    "CONCACAF Nations League qualification": 30,
    "African Nations Championship qualification": 30,
    "Atlantic Heritage Cup": 30,
    "Inter Games Football Tournament": 30,
    "CONCACAF Nations League": 30,
    "Three Nations Cup": 30,
    "Mahinda Rajapaksa Cup": 30,
    "Navruz Cup": 30,
    "CONIFA Africa Football Cup": 30,
    "CONIFA South America Football Cup": 30,
    "MSG Prime Minister's Cup": 30,
    "WM2022": 80
}